config/routes.rb
Rails.application.routes.draw do
  resources :contracts do
    member do
      get :show_rent_phase
    end
  end

end

app/models/contract.rb
class Contract < ActiveRecord::Base
  has_many :rent_phases
  has_many :invoices
  after_save :generate_invoices

  accepts_nested_attributes_for :rent_phases, allow_destroy: true
  accepts_nested_attributes_for :invoices, allow_destroy: true

  def generate_invoices
    length = self.rent_phases.count
    self.rent_phases.each_with_index do |rent_phase, index|
      total =
      if index == length -1
        diff_day = (rent_phase.end_date.day + 1) - (rent_phase.start_date).day
        if diff_day == 0
          ((rent_phase.end_date.year - rent_phase.start_date.year) * 12 +
          (rent_phase.end_date.month - rent_phase.start_date.month)) * rent_phase.price
        elsif diff_day > 0
          ((rent_phase.end_date.year - rent_phase.start_date.year) * 12 +
          (rent_phase.end_date.month - rent_phase.start_date.month)) * rent_phase.price +
          diff_day * (rent_phase.price * 12)/365.0
        else
          diff_month = rent_phase.end_date.month - rent_phase.start_date.month
          diff_month = diff_month == 0 ? 0 : (diff_month - 1)
          ((rent_phase.end_date.year - rent_phase.start_date.year) * 12 + diff_month) * rent_phase.price + (rent_phase.end_date - (rent_phase.start_date + diff_month)) *
           (rent_phase.price * 12)/365.0
        end
      else
        (rent_phase.price * rent_phase.cycles)
      end
        invoice_query = {
          start_date: rent_phase.start_date,
          end_date: rent_phase.end_date,
          due_date: Date.today,
          total: total,
          contract_id: self.id
        }
        Invoice.create(invoice_query)
    end
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_many :line_items
  belongs_to :contract

  after_save :create_line_items

  def create_line_items
    price = self.contract.try(:rent_phases).try(:first).try(:price).to_f
    invoice_end_date = self.end_date
    invoice_start_date = self.start_date
    diff_day = (invoice_end_date.day + 1) - (invoice_start_date).day
    if diff_day == 0
      (invoice_end_date.month - invoice_start_date.month).times do |mon|

        line_item_start_date = invoice_start_date + (mon-1).month
        line_item_end_date = (invoice_start_date + 1.month - 1.day) + (mon-1).month

        line_item_query = {
          start_date: line_item_start_date,
          end_date: line_item_end_date,
          unit_price: price,
          units: "1个月",
          total: price,
          invoice_id: self.id
        }
        LineItem.create(line_item_query)
      end
    elsif diff_day > 0
      (invoice_end_date.month - invoice_start_date.month).times do |mon|

        line_item_start_date = invoice_start_date + (mon-1).month
        line_item_end_date = (invoice_start_date + 1.month - 1.day) + (mon-1).month

        line_item_query = {
          start_date: line_item_start_date,
          end_date: line_item_end_date,
          unit_price: price,
          units: "1个月",
          total: price,
          invoice_id: self.id
        }
        LineItem.create(line_item_query)
      end
      day = invoice_end_date - ((line_item_start_date rescue nil) || invoice_start_date)
      line_item_day_query = {
        start_date: (line_item_start_date rescue nil) || invoice_start_date,
        end_date: invoice_end_date,
        unit_price: (price * 12)/365.0,
        units: "#{day.to_i}天",
        total: (price * 12)/365.0 * day,
        invoice_id: self.id
      }
      LineItem.create(line_item_day_query)
    else
      diff_month = self.end_date.month - self.start_date.month
      diff_month = diff_month == 0 ? 0 : (diff_month - 1)
      diff_month.times do |mon|

        line_item_start_date = invoice_start_date + (mon-1).month
        line_item_end_date = (invoice_start_date + 1.month - 1.day) + (mon-1).month

        line_item_query = {
          start_date: line_item_start_date,
          end_date: line_item_end_date,
          unit_price: price,
          units: "1个月",
          total: price,
          invoice_id: self.id
        }
        LineItem.create(line_item_query)
      end
      day = invoice_end_date - ((line_item_start_date rescue nil) || invoice_start_date)
      line_item_day_query = {
        start_date: (line_item_start_date rescue nil) || invoice_start_date,
        end_date: invoice_end_date,
        unit_price: (price * 12)/365.0,
        units: "#{day.to_i}天",
        total: (price * 12)/365.0 * day,
        invoice_id: self.id
      }
      LineItem.create(line_item_day_query)
    end
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :invoice
end

app/models/rent_phase.rb
class RentPhase < ActiveRecord::Base
  belongs_to :contract
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy, :show_rent_phase]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # 交租阶段显示
  def show_rent_phase
   @rent_phases = @contract.rent_phases
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_params
      params.require(:contract).permit(:start_date, :end_date, :name, :descrption,
        rent_phases_attributes: [:id, :start_date, :end_date, :price, :cycles, :_destroy],
        invoices_attributes: [:id, :start_date, :end_date, :due_date, :total, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= nested_form_for(@contract) do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descrption %><br>
    <%= f.text_area :descrption %>
  </div>
  <div>
    <%= f.fields_for :rent_phases do |rent_phase_form| %>
      <%= rent_phase_form.label :start_date %>:
      <%= rent_phase_form.text_field :start_date, { class: 'js_datepicker' }%>
      <%= rent_phase_form.label :end_date %>:
      <%= rent_phase_form.text_field :end_date, { class: 'js_datepicker' }%>
      <%= rent_phase_form.label :price %>:
      <%= rent_phase_form.text_field :price %>
      <%= rent_phase_form.label :cycles %>:
      <%= rent_phase_form.text_field :cycles %>
      <%= rent_phase_form.link_to_remove "Remove this rent_phase" %>
    <% end %>
    <p><%= f.link_to_add "Add a rent_phase", :rent_phases %></p>
  </div>

  <div>
    <%= f.fields_for :invoices do |invoice_form| %>
      <%= invoice_form.label :start_date %>:
      <%= invoice_form.text_field :start_date %>
      <%= invoice_form.label :end_date %>:
      <%= invoice_form.text_field :end_date %>
      <%= invoice_form.label :due_date %>:
      <%= invoice_form.text_field :due_date %>
      <%= invoice_form.label :total %>:
      <%= invoice_form.text_field :total %>
      <%= invoice_form.link_to_remove "Remove this invoice" %>
    <% end %>
    <p><%= f.link_to_add "Add a invoice", :invoices %></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contracts</h1>

<table>
  <thead>
    <tr>
      <th>合同名称</th>
      <th>开始时间</th>
      <th>结束时间</th>
      <th>描述</th>
      <th colspan="4">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.name %></td>
        <td><%= l contract.start_date %></td>
        <td><%= l contract.end_date %></td>
        <td><%= contract.descrption %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to '交租阶段', show_rent_phase_contract_path(contract), target: "_blank" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<h1>New Contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @contract.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @contract.end_date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @contract.name %>
</p>

<p>
  <strong>Descrption:</strong>
  <%= @contract.descrption %>
</p>

<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/show_rent_phase.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>开始时间</th>
      <th>结束时间</th>
      <th>价格</th>
      <th>租期</th>
    </tr>
  </thead>

  <tbody>
    <% @rent_phases.each do |rent_phase| %>
      <tr>
        <td><%= rent_phase.start_date %></td>
        <td><%= rent_phase.end_date %></td>
        <td><%= rent_phase.price %></td>
        <td><%= rent_phase.cycles %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContractApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>